# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('numero_fiscal', models.DecimalField(decimal_places=5, max_digits=18)),
            ],
        ),
        migrations.AddField(
            model_name='dadosempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuning.Empresa'),
        ),
    ]
